import type { TransactionCategory } from './types';

// Each entry: [keyword (lowercase), category]
// Checked in order — first match wins.
export const DEFAULT_RULES: Array<[string, TransactionCategory]> = [
  // ── Transfers & income ────────────────────────────────────────────────────
  ['zelle',           'transfer'],
  ['wire transfer',   'transfer'],
  ['transfer from',   'transfer'],
  ['transfer to',     'transfer'],
  ['deposit from',    'transfer'],
  ['withdrawal to',   'transfer'],
  ['payroll',         'income'],
  ['direct deposit',  'income'],
  ['ach deposit',     'income'],
  ['tax refund',      'income'],
  ['interest earned', 'income'],

  // ── Food & dining ─────────────────────────────────────────────────────────
  ['doordash',        'food'],
  ['uber eats',       'food'],
  ['grubhub',         'food'],
  ['instacart',       'food'],
  ['chipotle',        'food'],
  ['mcdonald',        'food'],
  ['starbucks',       'food'],
  ['chick-fil-a',     'food'],
  ['wendys',          'food'],
  ['dominos',         'food'],
  ['pizza',           'food'],
  ['subway',          'food'],
  ['taco bell',       'food'],
  ['panera',          'food'],
  ['dunkin',          'food'],
  ['whole foods',     'food'],
  ['trader joe',      'food'],
  ['kroger',          'food'],
  ['publix',          'food'],
  ['safeway',         'food'],
  ['wegmans',         'food'],
  ['aldi',            'food'],
  ['costco',          'food'],
  ['sam\'s club',     'food'],
  ['restaurant',      'food'],
  ['cafe',            'food'],
  ['diner',           'food'],
  ['bakery',          'food'],
  ['sushi',           'food'],
  ['burrito',         'food'],
  ['grocery',         'food'],
  ['supermarket',     'food'],

  // ── Transport ─────────────────────────────────────────────────────────────
  ['uber',            'transport'],
  ['lyft',            'transport'],
  ['waymo',           'transport'],
  ['shell',           'transport'],
  ['exxon',           'transport'],
  ['chevron',         'transport'],
  ['bp ',             'transport'],
  ['sunoco',          'transport'],
  ['marathon',        'transport'],
  ['speedway',        'transport'],
  ['fuel',            'transport'],
  ['gas station',     'transport'],
  ['parking',         'transport'],
  ['e-zpass',         'transport'],
  ['toll',            'transport'],
  ['tesla supercharg','transport'],
  ['amtrak',          'transport'],
  ['greyhound',       'transport'],
  ['southwest air',   'transport'],
  ['delta air',       'transport'],
  ['united air',      'transport'],
  ['american air',    'transport'],
  ['jetblue',         'transport'],
  ['airline',         'transport'],
  ['airport',         'transport'],
  ['rental car',      'transport'],
  ['enterprise rent', 'transport'],
  ['hertz',           'transport'],

  // ── Shopping ──────────────────────────────────────────────────────────────
  ['amazon',          'shopping'],
  ['walmart',         'shopping'],
  ['target',          'shopping'],
  ['bestbuy',         'shopping'],
  ['best buy',        'shopping'],
  ['home depot',      'shopping'],
  ['lowe\'s',         'shopping'],
  ['ikea',            'shopping'],
  ['ebay',            'shopping'],
  ['etsy',            'shopping'],
  ['apple store',     'shopping'],
  ['apple.com/bill',  'shopping'],
  ['gap',             'shopping'],
  ['old navy',        'shopping'],
  ['h&m',             'shopping'],
  ['zara',            'shopping'],
  ['nike',            'shopping'],
  ['adidas',          'shopping'],
  ['nordstrom',       'shopping'],
  ['macy\'s',         'shopping'],
  ['tj maxx',         'shopping'],
  ['marshalls',       'shopping'],
  ['dollar tree',     'shopping'],
  ['dollar general',  'shopping'],
  ['cvs',             'shopping'],
  ['walgreens',       'shopping'],
  ['rite aid',        'shopping'],

  // ── Entertainment ─────────────────────────────────────────────────────────
  ['netflix',         'entertainment'],
  ['hulu',            'entertainment'],
  ['disney+',         'entertainment'],
  ['disney plus',     'entertainment'],
  ['hbo max',         'entertainment'],
  ['max.com',         'entertainment'],
  ['peacock',         'entertainment'],
  ['paramount',       'entertainment'],
  ['apple tv',        'entertainment'],
  ['youtube',         'entertainment'],
  ['twitch',          'entertainment'],
  ['steam',           'entertainment'],
  ['playstation',     'entertainment'],
  ['xbox',            'entertainment'],
  ['nintendo',        'entertainment'],
  ['amc theater',     'entertainment'],
  ['regal',           'entertainment'],
  ['cinemark',        'entertainment'],
  ['ticketmaster',    'entertainment'],
  ['stubhub',         'entertainment'],
  ['spotify',         'entertainment'],
  ['apple music',     'entertainment'],
  ['tidal',           'entertainment'],
  ['audible',         'entertainment'],
  ['kindle',          'entertainment'],

  // ── Health ────────────────────────────────────────────────────────────────
  ['pharmacy',        'health'],
  ['cvs pharmacy',    'health'],
  ['walgreens pharmacy', 'health'],
  ['doctor',          'health'],
  ['dentist',         'health'],
  ['dental',          'health'],
  ['vision',          'health'],
  ['hospital',        'health'],
  ['urgent care',     'health'],
  ['medical',         'health'],
  ['health',          'health'],
  ['gym',             'health'],
  ['planet fitness',  'health'],
  ['equinox',         'health'],
  ['la fitness',      'health'],
  ['peloton',         'health'],

  // ── Utilities ─────────────────────────────────────────────────────────────
  ['electric',        'utilities'],
  ['water bill',      'utilities'],
  ['gas bill',        'utilities'],
  ['internet',        'utilities'],
  ['comcast',         'utilities'],
  ['xfinity',         'utilities'],
  ['verizon',         'utilities'],
  ['at&t',            'utilities'],
  ['t-mobile',        'utilities'],
  ['sprint',          'utilities'],
  ['utility',         'utilities'],
  ['phone bill',      'utilities'],
  ['cable bill',      'utilities'],

  // ── Subscriptions ─────────────────────────────────────────────────────────
  ['adobe',           'subscriptions'],
  ['microsoft 365',   'subscriptions'],
  ['office 365',      'subscriptions'],
  ['dropbox',         'subscriptions'],
  ['google storage',  'subscriptions'],
  ['icloud',          'subscriptions'],
  ['1password',       'subscriptions'],
  ['lastpass',        'subscriptions'],
  ['github',          'subscriptions'],
  ['openai',          'subscriptions'],
  ['chatgpt',         'subscriptions'],
  ['patreon',         'subscriptions'],
  ['substack',        'subscriptions'],
  ['duolingo',        'subscriptions'],
  ['headspace',       'subscriptions'],
  ['calm',            'subscriptions'],
  ['nytimes',         'subscriptions'],
  ['wsj',             'subscriptions'],
  ['subscription',    'subscriptions'],
  ['membership',      'subscriptions'],
];
