import type { TransactionCategory } from './types';

// Each entry: [keyword (lowercase), category]
// Checked in order — first match wins.
// Order matters: more specific patterns before generic ones (e.g. "uber eats" before "uber").
//
// Category taxonomy mirrors Chase / major-bank MCC mapping:
//   food         → MCCs 5411 (groceries), 5812-5814 (restaurants), 5441 (candy/bakery)
//   transport    → MCCs 5541-5542 (gas), 4111-4131 (transit), 4511 (airlines),
//                  7011 (hotels/travel), 7512-7514 (car rental), 7523 (parking)
//   shopping     → MCCs 5200-5999 (retail), 5310-5399 (discount stores)
//   entertainment→ MCCs 5813 (bars), 7832 (theaters), 7922-7999 (recreation)
//   health       → MCCs 5122 (pharmacy), 8011-8099 (health providers)
//   utilities    → MCCs 4800-4899 (telecoms), 4900-4999 (utilities)
//   subscriptions→ recurring SaaS / digital services (no distinct MCC)
//   income       → ACH deposits, payroll
//   transfer     → account-to-account moves, credit card payments
//   other        → fallback
export const DEFAULT_RULES: Array<[string, TransactionCategory]> = [

  // ── Transfers & payments (check before income — more specific) ────────────
  ['zelle',              'transfer'],
  ['wire transfer',      'transfer'],
  ['transfer from',      'transfer'],
  ['transfer to',        'transfer'],
  ['deposit from',       'transfer'],
  ['withdrawal to',      'transfer'],
  ['online transfer',    'transfer'],
  ['account transfer',   'transfer'],
  ['payment to',         'transfer'],
  ['autopay',            'transfer'],
  ['venmo',              'transfer'],
  ['cash app',           'transfer'],
  ['paypal transfer',    'transfer'],

  // ── Income ────────────────────────────────────────────────────────────────
  ['payroll',            'income'],
  ['direct deposit',     'income'],
  ['ach deposit',        'income'],
  ['tax refund',         'income'],
  ['interest earned',    'income'],
  ['dividend',           'income'],
  ['social security',    'income'],
  ['unemployment',       'income'],
  ['refund',             'income'],

  // ── Food & Dining — delivery first (more specific than bare "uber") ───────
  ['doordash',           'food'],
  ['uber eats',          'food'],
  ['grubhub',            'food'],
  ['postmates',          'food'],
  ['seamless',           'food'],
  ['instacart',          'food'],
  ['gopuff',             'food'],
  ['caviar',             'food'],

  // Fast food chains
  ['mcdonald',           'food'],
  ['chick-fil-a',        'food'],
  ['chickfila',          'food'],
  ['wendy',              'food'],
  ['burger king',        'food'],
  ['taco bell',          'food'],
  ['chipotle',           'food'],
  ['subway',             'food'],
  ['domino',             'food'],
  ['pizza hut',          'food'],
  ['papa john',          'food'],
  ['little caesar',      'food'],
  ['papa murphy',        'food'],
  ['five guys',          'food'],
  ['shake shack',        'food'],
  ['in-n-out',           'food'],
  ['wingstop',           'food'],
  ['raising cane',       'food'],
  ['popeye',             'food'],
  ['kfc',                'food'],
  ['jack in the box',    'food'],
  ['sonic drive',        'food'],
  ['sonic ',             'food'],
  ['arby',               'food'],
  ['dairy queen',        'food'],
  ['dq ',                'food'],
  ['culver',             'food'],
  ['whataburger',        'food'],
  ['jimmy john',         'food'],
  ['jersey mike',        'food'],
  ['firehouse sub',      'food'],
  ['panda express',      'food'],
  ['noodles',            'food'],
  ['potbelly',           'food'],

  // Coffee & cafés
  ['starbucks',          'food'],
  ['dunkin',             'food'],
  ['dutch bros',         'food'],
  ['coffee bean',        'food'],
  ['peet\'s',            'food'],
  ["peet's",             'food'],
  ['caribou coffee',     'food'],
  ['tim hortons',        'food'],
  ['coffee',             'food'],

  // Casual / sit-down / other food
  ['panera',             'food'],
  ['olive garden',       'food'],
  ['applebee',           'food'],
  ['chili\'s',           'food'],
  ["chili's",            'food'],
  ['ihop',               'food'],
  ['denny',              'food'],
  ['waffle house',       'food'],
  ['cracker barrel',     'food'],
  ['outback',            'food'],
  ['longhorn',           'food'],
  ['red lobster',        'food'],
  ['texas roadhouse',    'food'],
  ['buffalo wild wings', 'food'],
  ['hooters',            'food'],
  ['red robin',          'food'],
  ['dine brands',        'food'],
  ['cheesecake factory', 'food'],
  ['first watch',        'food'],
  ['eggs up grill',      'food'],
  ['sushi',              'food'],
  ['ramen',              'food'],
  ['pho',                'food'],
  ['thai',               'food'],
  ['indian restaurant',  'food'],
  ['pizza',              'food'],
  ['burrito',            'food'],
  ['taqueria',           'food'],
  ['bbq',                'food'],
  ['barbeque',           'food'],
  ['steakhouse',         'food'],
  ['seafood',            'food'],
  ['bakery',             'food'],
  ['bagel',              'food'],
  ['deli',               'food'],
  ['diner',              'food'],
  ['cafe',               'food'],
  ['bistro',             'food'],
  ['grill',              'food'],
  ['kitchen',            'food'],
  ['eatery',             'food'],
  ['restaurant',         'food'],
  ['bar & grill',        'food'],

  // Square / Toast POS (common for independent restaurants, cafés)
  ['sq *',               'food'],
  ['tst*',               'food'],

  // Grocery & supermarket
  ['whole foods',        'food'],
  ['trader joe',         'food'],
  ['kroger',             'food'],
  ['publix',             'food'],
  ['safeway',            'food'],
  ['wegmans',            'food'],
  ['aldi',               'food'],
  ['costco',             'food'],  // also gas/shopping — food wins for most trips
  ['sam\'s club',        'food'],
  ["sam's club",         'food'],
  ['bj\'s wholesale',    'food'],
  ["bj's wholesale",     'food'],
  ['h-e-b',              'food'],
  ['heb ',               'food'],
  ['meijer',             'food'],
  ['shoprite',           'food'],
  ['stop & shop',        'food'],
  ['giant food',         'food'],
  ['food lion',          'food'],
  ['harris teeter',      'food'],
  ['winn-dixie',         'food'],
  ['vons',               'food'],
  ['ralphs',             'food'],
  ['sprouts',            'food'],
  ['market basket',      'food'],
  ['price chopper',      'food'],
  ['smart & final',      'food'],
  ['winco',              'food'],
  ['stater bros',        'food'],
  ['brookshire',         'food'],
  ['ingles',             'food'],
  ['acme market',        'food'],
  ['grocery',            'food'],
  ['supermarket',        'food'],
  ['food mart',          'food'],
  ['fresh market',       'food'],

  // ── Transport — gas first (before generic "shell" etc.) ──────────────────
  ['shell oil',          'transport'],
  ['shell ',             'transport'],
  ['exxon',              'transport'],
  ['mobil',              'transport'],
  ['chevron',            'transport'],
  ['bp ',                'transport'],
  ['bp#',                'transport'],
  ['sunoco',             'transport'],
  ['marathon petro',     'transport'],
  ['marathon ',          'transport'],
  ['speedway',           'transport'],
  ['quiktrip',           'transport'],
  ['qt ',                'transport'],
  ['pilot flying',       'transport'],
  ['love\'s travel',     'transport'],
  ["love's travel",      'transport'],
  ['circle k',           'transport'],
  ['casey\'s general',   'transport'],
  ["casey's general",    'transport'],
  ['arco ',              'transport'],
  ['valero',             'transport'],
  ['76 ',                'transport'],
  ['murphy gas',         'transport'],
  ['murphy usa',         'transport'],
  ['racetrac',           'transport'],
  ['wawa ',              'transport'],
  ['kwik trip',          'transport'],
  ['maverik',            'transport'],
  ['fuel',               'transport'],
  ['gas station',        'transport'],

  // EV charging
  ['tesla supercharg',   'transport'],
  ['chargepoint',        'transport'],
  ['electrify america',  'transport'],
  ['evgo',               'transport'],
  ['blink charging',     'transport'],

  // Rideshare (uber AFTER uber eats — more specific wins above)
  ['uber',               'transport'],
  ['lyft',               'transport'],
  ['waymo',              'transport'],
  ['via ride',           'transport'],
  ['curb ',              'transport'],

  // Airlines
  ['southwest air',      'transport'],
  ['delta air',          'transport'],
  ['united air',         'transport'],
  ['american air',       'transport'],
  ['jetblue',            'transport'],
  ['alaska air',         'transport'],
  ['spirit airlines',    'transport'],
  ['frontier airlines',  'transport'],
  ['allegiant',          'transport'],
  ['hawaiian air',       'transport'],
  ['airline',            'transport'],
  ['airport',            'transport'],
  ['expedia',            'transport'],

  // Hotels & lodging
  ['marriott',           'transport'],
  ['hilton ',            'transport'],
  ['hyatt',              'transport'],
  ['westin',             'transport'],
  ['sheraton',           'transport'],
  ['holiday inn',        'transport'],
  ['hampton inn',        'transport'],
  ['courtyard by',       'transport'],
  ['fairfield inn',      'transport'],
  ['residence inn',      'transport'],
  ['springhill suite',   'transport'],
  ['best western',       'transport'],
  ['comfort inn',        'transport'],
  ['motel 6',            'transport'],
  ['super 8',            'transport'],
  ['days inn',           'transport'],
  ['la quinta',          'transport'],
  ['wyndham',            'transport'],
  ['ihg hotel',          'transport'],
  ['choice hotel',       'transport'],
  ['airbnb',             'transport'],
  ['vrbo',               'transport'],
  ['booking.com',        'transport'],
  ['hotels.com',         'transport'],
  ['hotel ',             'transport'],
  ['resort ',            'transport'],
  ['inn ',               'transport'],
  ['lodge ',             'transport'],

  // Car rental
  ['enterprise rent',    'transport'],
  ['hertz',              'transport'],
  ['avis ',              'transport'],
  ['budget rent',        'transport'],
  ['national car',       'transport'],
  ['alamo rent',         'transport'],
  ['zipcar',             'transport'],
  ['turo ',              'transport'],
  ['rental car',         'transport'],

  // Parking & transit
  ['e-zpass',            'transport'],
  ['ezpass',             'transport'],
  ['sunpass',            'transport'],
  ['peach pass',         'transport'],
  ['toll ',              'transport'],
  ['parking',            'transport'],
  ['sp plus',            'transport'],
  ['parkmobile',         'transport'],
  ['spothero',           'transport'],
  ['laz parking',        'transport'],
  ['impark',             'transport'],
  ['amtrak',             'transport'],
  ['greyhound',          'transport'],
  ['megabus',            'transport'],
  ['flixbus',            'transport'],
  ['metro card',         'transport'],
  ['transit',            'transport'],
  ['mta ',               'transport'],
  ['wmata',              'transport'],
  ['bart ',              'transport'],
  ['cta ',               'transport'],

  // Auto service
  ['jiffy lube',         'transport'],
  ['valvoline',          'transport'],
  ['pep boys',           'transport'],
  ['autozone',           'transport'],
  ['advance auto',       'transport'],
  ['o\'reilly auto',     'transport'],
  ["o'reilly auto",      'transport'],
  ['napa auto',          'transport'],
  ['car wash',           'transport'],
  ['dealer ',            'transport'],
  ['auto repair',        'transport'],
  ['tire ',              'transport'],

  // ── Shopping ──────────────────────────────────────────────────────────────
  ['amazon',             'shopping'],
  ['amzn',               'shopping'],
  ['walmart',            'shopping'],
  ['target',             'shopping'],
  ['best buy',           'shopping'],
  ['bestbuy',            'shopping'],
  ['home depot',         'shopping'],
  ['lowe\'s',            'shopping'],
  ["lowe's",             'shopping'],
  ['menards',            'shopping'],
  ['ace hardware',       'shopping'],
  ['true value',         'shopping'],
  ['ikea',               'shopping'],
  ['ebay',               'shopping'],
  ['etsy',               'shopping'],
  ['apple store',        'shopping'],
  ['apple.com/bill',     'shopping'],
  ['gap ',               'shopping'],
  ['old navy',           'shopping'],
  ['banana republic',    'shopping'],
  ['h&m',                'shopping'],
  ['zara',               'shopping'],
  ['nike',               'shopping'],
  ['adidas',             'shopping'],
  ['under armour',       'shopping'],
  ['nordstrom',          'shopping'],
  ['macy\'s',            'shopping'],
  ["macy's",             'shopping'],
  ['bloomingdale',       'shopping'],
  ['neiman marcus',      'shopping'],
  ['saks ',              'shopping'],
  ['tj maxx',            'shopping'],
  ['marshalls',          'shopping'],
  ['ross stores',        'shopping'],
  ['burlington coat',    'shopping'],
  ['forever 21',         'shopping'],
  ['abercrombie',        'shopping'],
  ['hollister',          'shopping'],
  ['american eagle',     'shopping'],
  ['bath & body',        'shopping'],
  ['victoria secret',    'shopping'],
  ['foot locker',        'shopping'],
  ['finish line',        'shopping'],
  ['pacsun',             'shopping'],
  ['anthropologie',      'shopping'],
  ['urban outfitter',    'shopping'],
  ['free people',        'shopping'],
  ['dollar tree',        'shopping'],
  ['dollar general',     'shopping'],
  ['five below',         'shopping'],
  ['michaels ',          'shopping'],
  ['hobby lobby',        'shopping'],
  ['joann',              'shopping'],
  ['tuesday morning',    'shopping'],
  ['tj maxx',            'shopping'],
  ['bealls',             'shopping'],
  ['office depot',       'shopping'],
  ['staples',            'shopping'],
  ['officemax',          'shopping'],
  ['petco',              'shopping'],
  ['petsmart',           'shopping'],
  ['chewy',              'shopping'],
  ['gamestop',           'shopping'],
  ['newegg',             'shopping'],
  ['b&h photo',          'shopping'],
  ['micro center',       'shopping'],
  ['fry\'s electronics', 'shopping'],
  ['wish ',              'shopping'],
  ['shein',              'shopping'],
  ['temu ',              'shopping'],
  ['wayfair',            'shopping'],
  ['overstock',          'shopping'],
  ['crate & barrel',     'shopping'],
  ['world market',       'shopping'],
  ['pier 1',             'shopping'],
  ['pottery barn',       'shopping'],
  ['restoration hardware','shopping'],
  ['williams-sonoma',    'shopping'],
  ['bed bath',           'shopping'],
  ['cvs',                'shopping'],
  ['walgreens',          'shopping'],
  ['rite aid',           'shopping'],

  // ── Entertainment ─────────────────────────────────────────────────────────
  // Streaming video
  ['netflix',            'entertainment'],
  ['hulu',               'entertainment'],
  ['disney+',            'entertainment'],
  ['disney plus',        'entertainment'],
  ['disneyplus',         'entertainment'],
  ['hbo max',            'entertainment'],
  ['max.com',            'entertainment'],
  ['peacock',            'entertainment'],
  ['paramount',          'entertainment'],
  ['apple tv',           'entertainment'],
  ['youtube premium',    'entertainment'],
  ['youtube',            'entertainment'],
  ['twitch',             'entertainment'],
  ['fubo',               'entertainment'],
  ['sling',              'entertainment'],
  ['directv',            'entertainment'],
  ['dazn',               'entertainment'],
  ['espn+',              'entertainment'],
  ['discovery+',         'entertainment'],

  // Gaming
  ['steam ',             'entertainment'],
  ['playstation',        'entertainment'],
  ['xbox',               'entertainment'],
  ['nintendo',           'entertainment'],
  ['epic games',         'entertainment'],
  ['ea.com',             'entertainment'],
  ['ubisoft',            'entertainment'],
  ['blizzard',           'entertainment'],
  ['activision',         'entertainment'],
  ['gamestop',           'entertainment'],

  // Music
  ['spotify',            'entertainment'],
  ['apple music',        'entertainment'],
  ['tidal',              'entertainment'],
  ['amazon music',       'entertainment'],
  ['siriusxm',           'entertainment'],
  ['pandora',            'entertainment'],

  // Tickets & events
  ['ticketmaster',       'entertainment'],
  ['stubhub',            'entertainment'],
  ['axs.com',            'entertainment'],
  ['live nation',        'entertainment'],
  ['seatgeek',           'entertainment'],

  // Theaters & venues
  ['amc theater',        'entertainment'],
  ['amc ',               'entertainment'],
  ['regal',              'entertainment'],
  ['cinemark',           'entertainment'],
  ['alamo drafthouse',   'entertainment'],

  // Books & audio
  ['audible',            'entertainment'],
  ['kindle',             'entertainment'],
  ['barnes & noble',     'entertainment'],
  ['scribd',             'entertainment'],

  // News
  ['new york times',     'entertainment'],
  ['nytimes',            'entertainment'],
  ['wsj.com',            'entertainment'],
  ['wsj ',               'entertainment'],
  ['washington post',    'entertainment'],
  ['la times',           'entertainment'],

  // ── Health ────────────────────────────────────────────────────────────────
  // Pharmacy (check before the shopping-assigned cvs/walgreens)
  ['cvs pharmacy',       'health'],
  ['walgreens pharmacy', 'health'],
  ['rite aid pharmacy',  'health'],
  ['pharmacy',           'health'],
  ['prescription',       'health'],

  // Medical providers
  ['doctor',             'health'],
  ['urgent care',        'health'],
  ['hospital',           'health'],
  ['medical center',     'health'],
  ['health system',      'health'],
  ['clinic',             'health'],
  ['dentist',            'health'],
  ['dental',             'health'],
  ['orthodont',          'health'],
  ['vision',             'health'],
  ['optometry',          'health'],
  ['lenscrafters',       'health'],
  ['warby parker',       'health'],
  ['1-800-contacts',     'health'],
  ['labcorp',            'health'],
  ['quest diagnostic',   'health'],
  ['radiology',          'health'],
  ['physical therapy',   'health'],
  ['chiropractic',       'health'],
  ['medical',            'health'],
  ['health ',            'health'],

  // Telehealth & mental health
  ['betterhelp',         'health'],
  ['talkspace',          'health'],
  ['cerebral',           'health'],
  ['teladoc',            'health'],

  // Fitness
  ['planet fitness',     'health'],
  ['equinox',            'health'],
  ['la fitness',         'health'],
  ['anytime fitness',    'health'],
  ['24 hour fitness',    'health'],
  ['gold\'s gym',        'health'],
  ["gold's gym",         'health'],
  ['crossfit',           'health'],
  ['orangetheory',       'health'],
  ['barry\'s',           'health'],
  ["barry's",            'health'],
  ['classpass',          'health'],
  ['soulcycle',          'health'],
  ['peloton',            'health'],
  ['ymca',               'health'],
  ['gym ',               'health'],
  ['fitness',            'health'],

  // ── Utilities ─────────────────────────────────────────────────────────────
  // Internet & cable
  ['xfinity',            'utilities'],
  ['comcast',            'utilities'],
  ['spectrum',           'utilities'],
  ['cox comm',           'utilities'],
  ['centurylink',        'utilities'],
  ['lumen',              'utilities'],
  ['frontier comm',      'utilities'],
  ['att.com',            'utilities'],
  ['at&t',               'utilities'],
  ['verizon',            'utilities'],
  ['t-mobile',           'utilities'],
  ['sprint',             'utilities'],
  ['us cellular',        'utilities'],
  ['boost mobile',       'utilities'],
  ['cricket wireless',   'utilities'],
  ['metro by t-mobile',  'utilities'],
  ['mint mobile',        'utilities'],
  ['republic wireless',  'utilities'],
  ['visible ',           'utilities'],
  ['internet',           'utilities'],
  ['cable ',             'utilities'],
  ['phone bill',         'utilities'],

  // Electric / gas / water
  ['duke energy',        'utilities'],
  ['dominion energy',    'utilities'],
  ['pg&e',               'utilities'],
  ['pge ',               'utilities'],
  ['con edison',         'utilities'],
  ['coned',              'utilities'],
  ['fpl ',               'utilities'],
  ['florida power',      'utilities'],
  ['georgia power',      'utilities'],
  ['southern company',   'utilities'],
  ['pacific gas',        'utilities'],
  ['national grid',      'utilities'],
  ['ameren',             'utilities'],
  ['centerpoint energy', 'utilities'],
  ['nicor gas',          'utilities'],
  ['atmos energy',       'utilities'],
  ['electric ',          'utilities'],
  ['gas bill',           'utilities'],
  ['water bill',         'utilities'],
  ['utility',            'utilities'],

  // Insurance (billed monthly like a utility)
  ['geico',              'utilities'],
  ['progressive ins',    'utilities'],
  ['state farm',         'utilities'],
  ['allstate',           'utilities'],
  ['liberty mutual',     'utilities'],
  ['nationwide ins',     'utilities'],
  ['usaa ',              'utilities'],
  ['farmers ins',        'utilities'],
  ['travelers ins',      'utilities'],
  ['insurance',          'utilities'],

  // ── Subscriptions ─────────────────────────────────────────────────────────
  // Creative / productivity SaaS
  ['adobe',              'subscriptions'],
  ['microsoft 365',      'subscriptions'],
  ['office 365',         'subscriptions'],
  ['microsoft*',         'subscriptions'],
  ['dropbox',            'subscriptions'],
  ['google one',         'subscriptions'],
  ['google storage',     'subscriptions'],
  ['icloud',             'subscriptions'],
  ['apple one',          'subscriptions'],
  ['1password',          'subscriptions'],
  ['lastpass',           'subscriptions'],
  ['bitwarden',          'subscriptions'],
  ['dashlane',           'subscriptions'],
  ['notion',             'subscriptions'],
  ['evernote',           'subscriptions'],
  ['grammarly',          'subscriptions'],
  ['canva',              'subscriptions'],
  ['figma',              'subscriptions'],
  ['zoom',               'subscriptions'],
  ['slack',              'subscriptions'],
  ['github',             'subscriptions'],
  ['digitalocean',       'subscriptions'],
  ['linode',             'subscriptions'],
  ['aws ',               'subscriptions'],
  ['amazon web service', 'subscriptions'],
  ['azure ',             'subscriptions'],
  ['google cloud',       'subscriptions'],
  ['heroku',             'subscriptions'],
  ['cloudflare',         'subscriptions'],
  ['openai',             'subscriptions'],
  ['chatgpt',            'subscriptions'],
  ['anthropic',          'subscriptions'],
  ['nordvpn',            'subscriptions'],
  ['expressvpn',         'subscriptions'],
  ['protonvpn',          'subscriptions'],
  ['protonmail',         'subscriptions'],

  // Learning & community
  ['patreon',            'subscriptions'],
  ['substack',           'subscriptions'],
  ['duolingo',           'subscriptions'],
  ['headspace',          'subscriptions'],
  ['calm',               'subscriptions'],
  ['masterclass',        'subscriptions'],
  ['coursera',           'subscriptions'],
  ['udemy',              'subscriptions'],
  ['linkedin premium',   'subscriptions'],

  // Generic trailing catches
  ['subscription',       'subscriptions'],
  ['membership',         'subscriptions'],
  ['monthly plan',       'subscriptions'],
  ['annual plan',        'subscriptions'],
];
